---
  - name: remove nginx mainline repo
    apt_repository: repo='deb http://nginx.org/packages/mainline/ubuntu/ trusty nginx' state=absent

  - name: add nginx-repo-key
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: ABF5BD827BD9BF62
      state: present

  - name: add nginx stable repository
    apt_repository:
      repo: deb http://nginx.org/packages/ubuntu/ trusty nginx
      update_cache: yes

  - name: install nginx
    action: apt name=nginx update_cache=yes state=latest

  - name: Replace nginx config file
    action: template src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf

  - name: Replace nginx config file
    action: template src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

  - name: Add Users ubuntu to www-data
    action: user name=ubuntu groups="www-data" append=yes

  - name: Create sites-avalaible folder
    file:
      path: /etc/nginx/sites-avalaible
      recurse: yes
      state: directory
      mode: 0755

  - name: Create sites-enabled folder
    file:
      path: /etc/nginx/sites-enabled
      recurse: yes
      state: directory
      mode: 0755

#- name: Add index.php with template
#    action: template src=index.php.j2 dest=/var/www/nginx-default/index.php
